spring:
  application:
    name: SecureVault
  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true
server:
  servlet:
    session:
      timeout: 20m
      # Force the session cookie to be marked 'Secure' (Required for HTTPS browsers)
      cookie:
        secure: true
        # Use 'Lax' so the cookie is sent during the form post
        same-site: lax

  # Tell Spring to trust the 'X-Forwarded-Proto' header from your host (e.g., Render/AWS)
  forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    enable:
        all: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT_METRICS:http://localhost:4318/v1/metrics}
        step: 10s
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT_TRACES:http://localhost:4318/v1/traces}