spring:
  application:
    name: SecureVault
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env.development[.properties]

server:
  servlet:
    session:
      timeout: 20m

