name: Trigger auto deployment for secure-vault-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/secure-vault-container-AutoDeployTrigger-1d99e437-196e-4993-ac72-a9366925e1fa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SECUREVAULTCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SECUREVAULTCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SECUREVAULTCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Dockerfile.prod
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrsecurevultprod-fabudmgwayb2enc2.azurecr.io
          registryUsername: ${{ secrets.SECUREVAULTCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SECUREVAULTCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: secure-vault-container
          resourceGroup: rg-secure-vault
          imageToBuild: acrsecurevultprod-fabudmgwayb2enc2.azurecr.io/secure-vault-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


